### ISSUE TITLE
인용표시의 건

### ISSUE THREAD

**Issue by pesusjay** [mingi3314/postly#11]
1. 표기법 
방송/전시/영화/책  ->  <>
앨범명  -> []
음원, 공연 -> '' 

2. 모바일 이미지
모바일로 해당 링크 접속시 반응형 작동이 안됨.
길게 늘어지는 이슈 발생
![KakaoTalk_20240903_142534223](https://github.com/user-attachments/assets/9827ca1e-b20a-458d-9f55-5775733bc321)

**Comment by mingi3314** [comment]
제안해주셔서 감사드려요 : )

표기법 관련해서는 https://github.com/mingi3314/postly/pull/13 PR에서 프롬프트 개선과 함께 적용해두었습니다.

모바일 반응형 작동 관련해서는 좀 더 살펴본 후 작업하도록 하겠습니다 : )
